# Generated by Django 4.2 on 2024-02-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.ImageField(
                blank=True, default="generated.png", null=True, upload_to=""
            ),
        ),
    ]
