# Generated by Django 4.2 on 2024-02-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
