# Generated by Django 4.2 on 2024-02-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_post_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
