# Generated by Django 4.2 on 2024-02-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_onboarded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="onboarded",
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profiles/default_user.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
