# Generated by Django 4.2 on 2024-02-18 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profile_onboarded_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ai_credit",
            field=models.IntegerField(
                default=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
