# Generated by Django 4.2 on 2024-02-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_ai_credit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="ai_credit",
            new_name="ai_credits",
        ),
    ]
